//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourcesClient.ResourceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ResourceService.IResourcesService")]
    public interface IResourcesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourcesService/GetResources", ReplyAction="http://tempuri.org/IResourcesService/GetResourcesResponse")]
        string GetResources();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourcesService/GetResources", ReplyAction="http://tempuri.org/IResourcesService/GetResourcesResponse")]
        System.Threading.Tasks.Task<string> GetResourcesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResourcesServiceChannel : ResourcesClient.ResourceService.IResourcesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResourcesServiceClient : System.ServiceModel.ClientBase<ResourcesClient.ResourceService.IResourcesService>, ResourcesClient.ResourceService.IResourcesService {
        
        public ResourcesServiceClient() {
        }
        
        public ResourcesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResourcesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourcesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourcesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetResources() {
            return base.Channel.GetResources();
        }
        
        public System.Threading.Tasks.Task<string> GetResourcesAsync() {
            return base.Channel.GetResourcesAsync();
        }
    }
}
